name: Lint

on: pull_request

jobs:
  lint:
    name: Run linters on PR
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: eslint
        uses: stefanoeb/eslint-action@1.0.2
      - name: hadolint
        uses: burdzwastaken/hadolint-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HADOLINT_ACTION_DOCKERFILE_FOLDER: ./apollo
